/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_allen_androidcommonexample_jni_JNIUtils */

#ifndef _Included_com_allen_androidcommonexample_jni_JNIUtils
#define _Included_com_allen_androidcommonexample_jni_JNIUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_allen_androidcommonexample_jni_JNIUtils
 * Method:    getWrold
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_allen_androidcommonexample_jni_JNIUtils_getWrold
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
